### ISSUE TITLE
Processing multiple samples

### ISSUE THREAD

**Issue by tbazilegith** [rpetit3/dragonflye#10]
Hi Robert,
Can dragonflye process multiple samples? How do I indicate that in the output directory ? Is there a flag for sample?
Thanks,
TJ

**Comment by rpetit3** [comment]
Hi TJ,

Dragonflye can pnly process one sample at a time. I think if you would like to process multiple samples it would be best handled by a workflow manager (e.g. Nextflow, Cromwell, etc).

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @tbazilegith 

Going to go ahead and close this issue, please feel free to reopen!

Cheers,
Robert
