### ISSUE TITLE
Memory default

### ISSUE THREAD

**Issue by lskatz** [rpetit3/dragonflye#15]
I'm wondering if you want to increase the default memory up to something more solid since this is nanopore.  64G?  The Java error that results is really confusing to people who don't know java.  I have one more separate but related idea and will make a separate ticket for that.

**Comment by rpetit3** [comment]
Hi @lskatz 

Which step is giving you issues? I'm hesitant to increase the default ram due to many not having access to systems with greater amounts (e.g. just laptops and desktops).

Cheers,
Robert

**Comment by lskatz** [comment]
It's pilon.  I'll try to get that error message for you.

**Comment by rpetit3** [comment]
Do you think exposing `-Xmx` for pilon, so that `--ram` could easily alter it be an ok solution for now? Until a potential solution is made with regards to the memory calculation issue

**Comment by lskatz** [comment]
I think that `--ram` is fine but it translates to the `-Xmx` option which might not have exactly the same meaning.  With `--ram`, it _tries_ to keep the memory down, but with `-Xmx`, it will die on error.  It might be fine just redefining `--ram` to mean the maximum memory allowed.  It's not an exact solution to this issue but it will be easier to implement.  I also know that this is an inherited issue and not something that you necessarily implemented yourself.

**Comment by rpetit3** [comment]
Hi @lskatz 

Similar to the previous issue, I'm going to let workflow managers and pipeline developers handle this. Feel free to reopen if you think otherwise.

Cheers,
Robert
