### ISSUE TITLE
Memory calculation

### ISSUE THREAD

**Issue by lskatz** [rpetit3/dragonflye#16]
I'm wondering if there is a way to estimate the memory requirements up front so that it doesn't produce an error.  Is that even possible?  Thinking about pilon but it's possible something else on here takes more memory?  If it's insufficient memory, then I'd suggest dragonfly produces an up front error.

**Comment by rpetit3** [comment]
I think with a lot of runs we could potentially estimate the amount of memory needed.

Curious, what size genome and estimated short read coverage was giving you issues?

**Comment by lskatz** [comment]
Default 16G memory and then the assembly size is around 4.8M.  I'm not sure what the original coverage is.  Trying to rope in my colleague to get all the details :)

**Comment by rpetit3** [comment]
Hi @lskatz 

I'm thinking I will let workflow managers and pipeline developers handle this. If you've come up with a solution for this or would like to revisit, please feel free to reopen.

Cheers,
Robert
