### ISSUE TITLE
Feature request: dragonflye 1.1.N default to flye 2.9.2?

### ISSUE THREAD

**Issue by incoherentian** [rpetit3/dragonflye#18]
Hi @rpetit3 - flye 2.9.2 is on bioconda now :) 

Do you think any major changes will be required for flye 2.9.2? Wondering if that would be fairly safe to pin &/or if you've done anything with it yet!

P.S. totally unrelated, but having the CPU/GPU version separated on bioconda was a great idea. I've only tried CPU medaka so far on 1.1.0. Is dragonflye-gpu on your dev channel?

**Comment by rpetit3** [comment]
Probably not, but I would need to check the changes. But leaning towards no. 

Definitely can pin it to the most recent versions. I think you could do something like

```
mamba create -n dragonflye -c conda-forge -c bioconda dragonflye 'flye=2.9.2'`
```

I really want to get a separate `dragonflye-gpu` version, but there's currently and issue solving the environment. I was unable to get it working through the Bioconda CI. The errors were related to CUDA, which the CI definitely doesn't have.

But I think workaround would be:

```
mamba create -n dragonflye-gpu -c conda-forge -c bioconda dragonflye tensorflow-gpu
```

**Comment by incoherentian** [comment]
> I really want to get a separate `dragonflye-gpu` version, but there's currently and issue solving the environment

Ah, the release notes made me think `dragonflye-gpu`  was already floating around somewhere!

> Release to separate Dragonflye to `dragonflye` and `dragonflye-gpu` on Bioconda

**Comment by rpetit3** [comment]
Hi @incoherentian 

That was my intentions, but unfortunately when trying to build a separate `dragonflye-gpu` I was unable to get the CI over on Bioconda to solve the environment properly. I think it had something to do with the CUDA version on the CI and tensorflow, but that was as far as I could take it.

For now my work around above will be the way to go. I also don't have a GPU that I can test things on, so I'm depending on user feedback on this one.

Cheers, apologies for the delay in responding! 
Robert

Going to go ahead and close this, please feel free to reopen
