### ISSUE TITLE
mm2 CPU count for mapping

### ISSUE THREAD

**Issue by chrisgulvik** [rpetit3/dragonflye#2]
When mapping with `minimap2`, it uses INT+1 the specified CPU count. Unsure if you think it's worth changing though because it would then require `dragonflye` to be a 2+ CPU process. According to the [man page](https://lh3.github.io/minimap2/minimap2.html) "the extra thread is for I/O" and "is frequently idle and takes little CPU time"

This is the only system call that does alignment and could have a $cpus - 1

- https://github.com/rpetit3/dragonflye/blob/main/bin/dragonflye#L274

**Comment by rpetit3** [comment]
Hi @chrisgulvik! 

Good call! I wasn't aware of that, I like your suggestion of `cpu - 1` to be explicit and especially for situations where CPU requirements are strict (e.g. job schedulers, containers, etc...)

Thank you very much for the feedback

**Comment by rpetit3** [comment]
This is available in v1.0.4 https://github.com/rpetit3/dragonflye/releases/tag/v1.0.4

Thank you very much for the feedback! Don't hesitate to reach out if you have more.
