### ISSUE TITLE
Niche QoL inquiry: polypolish acceptance of nonstandard file affixes?

### ISSUE THREAD

**Issue by incoherentian** [rpetit3/dragonflye#21]
Hi Robert,

Is there any way for dragonflye to accept nonstandard file inputs for polypolish?

e.g. get some version of this (fq.gz for R1/R2) working:
```
dragonflye\
 --cpus 12\
 --ram 12\
 --reads $RUN/gpy646sup/${SAMPLE}_merged_barcode*.fastq.gz\
 --R1 $RUN/d40_JING_out/output/${SAMPLE}*/${SAMPLE}*_val_1.fq.gz\
 --R2 $RUN/d40_JING_out/output/${SAMPLE}*/${SAMPLE}*_val_2.fq.gz\
 --depth 0\
 --nanohq\
 --medaka 2\
 --model r1041_e82_400bps_sup_g615\
 --polypolish 1\
 --outdir $OUTDIR/${SAMPLE}_dflye_m180p_out\
 --force  || echo "dflye error in i=$i"
```

instead of this (standard fastq.gz):
```
dragonflye\
 --cpus 12\
 --ram 12\
 --reads $RUN/gpy646sup/${SAMPLE}_merged_barcode*.fastq.gz\
 --R1 $RUN/d40_JING_out/output/${SAMPLE}*/${SAMPLE}*_val_1.fastq.gz\
 --R2 $RUN/d40_JING_out/output/${SAMPLE}*/${SAMPLE}*_val_2.fastq.gz\
 --depth 0\
 --nanohq\
 --medaka 2\
 --model r1041_e82_400bps_sup_g615\
 --polypolish 1\
 --outdir $OUTDIR/${SAMPLE}_dflye_m180p_out\
 --force  || echo "dflye error in i=$i"
```

I copy the `.fastq.gz` as `.fq.gz` and use the version immediately above for now, but I imagine there must be some less-bad way to just use the erstwhile-usable poorly-named files from another pipeline. (I still haven't been able to get bactopia-dev to spin up singularity containers with our SLURM nodes.)

Continued thanks for your amazing work either way!

**Comment by rpetit3** [comment]
@incoherentian I wasn't aware it acted in this way! Let me see if I can replicate, then sure we should be able to make it to where it doesn't care.

Feel free to reach out to me about the SLURM/Nextflow/Singularity

**Comment by rpetit3** [comment]
@incoherentian I finally got a chance to try this, and was unable to replicate. Have some files I might be able to test with?

**Comment by incoherentian** [comment]
Arg, sorry @rpetit3, I more recently swapped out the ancient version of trimgalore I was preprocessing short reads with for https://github.com/FelixKrueger/TrimGalore/tree/0.6.10 & haven't experienced that issue (nor several others) since. Seems pretty clear I was misinterpreting whatever the problem was in the first place. Very sorry I didn't update you on that!

I see this was from before I even had Singularity working. Singularity is also working a charm now, even the assembly container with medaka polishing after changes from the new dev build. Thanks soooo much for SO much help!

**Comment by rpetit3** [comment]
No problem! My favorite kind of fix! Glad things are running well for you now!
