### ISSUE TITLE
Coverage of "0"?

### ISSUE THREAD

**Issue by MalbertRogers** [rpetit3/dragonflye#24]
What does a coverage of 0 (for a config) in the "flye-info.txt" mean? I don't think these contigs end up in the final assembly file anyway, but I am curious as to how and why it is being reported as such, since it obviously doesn't make much sense.

**Comment by rpetit3** [comment]
I apologize for the very late response to this. 

I tried to dig this out of the Flye repo (https://github.com/fenderglass/Flye), and could not come to a conclusion on what it means to have 0 coverage. 

I wonder if it is worth asking over on the Flye repo?

**Comment by incoherentian** [comment]
Flye is probably only using the best match when calculating read coverage post-contig-generation. Odd that Flye generated those artifact contigs to start with, but them not being in the final assembly just shows that Flye / dragonflye is doing its job well :)

**Comment by rpetit3** [comment]
Hi @MalbertRogers 

I'm going to go ahead and close this, please feel free to reopen
