### ISSUE TITLE
Polypolish error 

### ISSUE THREAD

**Issue by andreagpo** [rpetit3/dragonflye#25]
Hi!

I'm trying to run dragonflye (v1.1.2) with default parameters using --reads, --R1 and --R2 inputs. The issue arises after assembling with flye, when dragonflye executes  polypolish (v0.6.0):
Running: polypolish flye/polish/racon/1/consensus.fasta flye/polish/short_reads/polypolish/1/polypolish_R1-1.sam flye/polish/short_reads/polypolish/1/polypolish-R2-1.sam > flye/polish/short_reads/polypolish/1/polypolish-1.fasta | sed 's/^/[short read polishing - polypolish (1 of 1)] /' | tee -a dragonflye.log

Error running command: polypolish flye/polish/racon/1/consensus.fasta flye/polish/short_reads/polypolish/1/polypolish_R1-1.sam flye/polish/short_reads/polypolish/1/polypolish-R2-1.sam > flye/polish/short_reads/polypolish/1/polypolish-1.fasta | sed 's/^/[short read polishing - polypolish (1 of 1)] /' | tee -a dragonflye.log

error: unrecognized subcommand 'flye/polish/racon/1/consensus.fasta'

I believe the issue is that the polish command is missing when calling polypolish.

Thanks for your hard work!

Andrea

**Comment by rpetit3** [comment]
Hi @andreagp96, What operating system are you working on?

**Comment by andreagpo** [comment]
Hello! I'm working on macOS (Ventura v13.6.4) :)

**Comment by rpetit3** [comment]
Do you by chance have access to "Docker Desktop"?

**Comment by andreagpo** [comment]
Mmm, I don't have access to "Docker Desktop". However, I was able to resolve the issue by modifying the dragonflye script using VIM. I added the command "polish" in line 414 as follows:

run_cmd("polypolish **polish** $POLISHED_FASTA $SAM_R1 $SAM_R2 > $round_dir/polypolish-$i.fasta", "short read polishing - polypolish ($i of $polypolish)");

instead of:

run_cmd("polypolish $POLISHED_FASTA $SAM_R1 $SAM_R2 > $round_dir/polypolish-$i.fasta", "short read polishing - polypolish ($i of $polypolish)");

Hoping this info is useful.

Kind regards,

Andrea

**Comment by rpetit3** [comment]
This is super helpful! Thank you so much! I did not realize some changes in the most recent version of polypolish: https://github.com/rrwick/Polypolish/releases/tag/v0.6.0

I will update Dragonflye to pin the minimum version of polypolish to 0.6.0

**Comment by andreagpo** [comment]
Happy to help!!

Thank you for your time and dedication,

Andrea
