### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Daniel-VM** [rpetit3/dragonflye#26]
Hello, is there a specific citation format available for Dragonflye?

**Comment by rpetit3** [comment]
There currently is not a published manuascript for Dragnflye.

you can use this:

Petit III, R. A. dragonflye: assemble bacterial isolate genomes from Nanopore reads (Version 1.1.2). https://github.com/rpetit3/dragonflye

**Comment by Daniel-VM** [comment]
Thanks 👍🏾
