### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by stas-malavin** [rpetit3/dragonflye#27]
```[dragonflye] Dragonfly larva eat just about anything: tadpoles, mosquitoes, fish, other insect larvae and even each other!```
Either 'larvae eat' or 'larva eats'.
Everything should be just perfect :)
Thanks for this nice piece of software!

**Comment by rpetit3** [comment]
Hi @stas-malavin 

Thank you for reporting the typo, I have fixed it and it will be available in next release.

Cheers,
Robert
