### ISSUE TITLE
Citation for Nanoq in readme - suggested update

### ISSUE THREAD

**Issue by matthewlinks** [rpetit3/dragonflye#28]
I was checking some references (to cite dragonflye and the tools used within it) and think the Nanoq citation in the readme could be updated to 

Steinig and Coin (2022). Nanoq: ultra-fast quality control for nanopore reads. Journal of Open Source Software, 7(69), 2991, https://doi.org/10.21105/joss.02991

cheers, 

Matt

**Comment by rpetit3** [comment]
Hi @matthewlinks 

Thank you for reporting, I've updated the citation.

Cheers,
Robert
