### ISSUE TITLE
Filtering reads quality

### ISSUE THREAD

**Issue by chen1i6c04** [rpetit3/dragonflye#3]
Hi

The ```dragonflye``` use ```nanoq``` filter reads length, and ```nanoq``` also can filter reads quality, could you add the feature to ```dragonflye```?

Thanks

**Comment by rpetit3** [comment]
Sure can! I'll look into it and get it in the next version

**Comment by rpetit3** [comment]
Thank you very much for the suggestion!

**Comment by rpetit3** [comment]
I've added `--minquality` to do quality filtering with nanoq. By default this is disabled.

https://github.com/rpetit3/dragonflye/releases/tag/v1.0.5

Thanks again for your suggestion
