### ISSUE TITLE
Execution error with Rasusa v1.0.0 in conda environment

### ISSUE THREAD

**Issue by nbenzakour** [rpetit3/dragonflye#31]
Hi,

Thanks for developing Dragonflye—it's been highly useful! I've encountered an issue with Rasusa during installation on a new Ubuntu 22.04 machine using Conda. Dragonflye v1.2.0 seems to pull Rasusa v1.0.0 instead of v0.8.0, leading to a syntax error in the rasusa command.

```
[...]
[dragonflye] Using rasusa - /opt/conda/envs/dragonflye_1.2.0/bin/rasusa | rasusa 1.0.0
[...]
[dragonflye] Running: rasusa -i READS\.filt\.fq\.gz -c 100 -g 50000 -s 42  2>&1 1> READS.sub.fq | sed 's/^/[rasusa] /' | tee -a dragonflye.log
[rasusa] error: unexpected argument '-i' found
[...]
```

Correct Rasusa v1.0.0 syntax:

```
rasusa reads -c 100 -g 50000 -s 42 READS\.filt\.fq\.gz 2>&1 1> READS.sub.fq | sed 's/^/[rasusa] /' | tee -a dragonflye.log
```

Cheers,
Nouri

**Comment by rpetit3** [comment]
Hi @nbenzakour 

Thank you for reporting this and especially for sharing the new syntax. I've now fixed this, just trying to sort out the CI before submitting a new release.

Cheers,
Robert

**Comment by rpetit3** [comment]
Ok submitted a new release, https://github.com/rpetit3/dragonflye/releases/tag/v1.2.1

I'll get the bioconda recipe updated as well. Thanks again!
