### ISSUE TITLE
Can't locate FindBin.pm in @INC

### ISSUE THREAD

**Issue by erinyoung** [rpetit3/dragonflye#33]
I don't know if this will be an issue to most of your users, but I installed dragonflye via micromamba in a gitpod environment and ran into the following error:

```
$ dragonflye --help
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /opt/conda/bin/dragonflye line 58.
BEGIN failed--compilation aborted at /opt/conda/bin/dragonflye line 58.
```

**Comment by erinyoung** [comment]
This issue resolves itself if I install FindBin with cpan. I just wanted to let you know that I encountered an error.

**Comment by rpetit3** [comment]
Thank you for sharing this find. I have not observed this on GitPod using this setup https://github.com/rpetit3/dragonflye/blob/main/.gitpod.yml

If it still persists feel free to reopen
