### ISSUE TITLE
homologous polishing

### ISSUE THREAD

**Issue by onertipaday** [rpetit3/dragonflye#4]
Hi Robert,
First of all thank you for this useful tool. I'd like to suggest to add [homopolish](https://github.com/ythuang0522/homopolish) as a further polishing step (step 6.5?) in the pipeline.

**Comment by rpetit3** [comment]
Hi @onertipaday 

I will totally look into this. At first glance it looked straight forward enough

Thank you very much for the suggestion!

**Comment by onertipaday** [comment]
I thank you for the great tool! Keep up the good work!

**Comment by rpetit3** [comment]
Hi @onertipaday , 

I'm a bit bummed, but unfortunately not going to be able to add homopolish at the moment. 

Currently an environment with medaka and homopolish cannot be solved with conda. I'll periodically check if they become compatible with one another. 

Going to close this for now, if by chance you figure out a working combination, please feel free to reopen!
Robert
