### ISSUE TITLE
Stuck in kmc part

### ISSUE THREAD

**Issue by llk578496** [rpetit3/dragonflye#5]
Hi @rpetit3 ,

Thank you for developing this tool! It is amazing.

I have just tried to run this tool, but sometimes it stuck in the kmc and doesn't continue running (I checked the cpu usage from htop). I quit the terminal and rerun again with option `--force`. The run will then be successfully completed. May I know how to solve this problem?

Thank you very much!

**Comment by rpetit3** [comment]
Hi @llk578496, 

Do you by chance know the genome size of the organism your assembling? If you do then you can use `--gsize` to skip the KMC step.

In the future I plan to replace KMC because it causes issues as well on my system.

**Comment by llk578496** [comment]
Hi @rpetit3 ,

Yes, I am working on Enterococcus faecium which ranges from around 2.5 to 3.16 Mb. May I know it is ok to use 3.16 Mb for the `--gsize`?
