### ISSUE TITLE
Unable to verify model 'r941_min_sup_g507'

### ISSUE THREAD

**Issue by llk578496** [rpetit3/dragonflye#6]
Hi @rpetit3 ,

We tried to polish the contigs with model `r941_min_sup_g507`, but we get these error message:

> [dragonflye] Verifying input model (--model): r941_min_sup_g507
> [dragonflye] Unable to verify model 'r941_min_sup_g507', please check spelling and try again.

May I know is this model included in dragonflye?

**Comment by rpetit3** [comment]
Hi @llk578496 , you can use `--list_models` to get the available models. Let me know if this helps

**Comment by ArnieBerg** [comment]
I am also getting this error now (Ubuntu 18.04). Just installed DragonFlye with conda. The real reason the error occurs is the --list_models does not return the available models. This was working previously. I need a fix.

**Comment by rpetit3** [comment]
Hi @ArnieBerg,

I will look into this. Please just keep in mind Dragonflye is a tool a maintain in my free time, so, I can't give a timeframe on this issue.

If you have a solution, please feel free to submit a pull request.

Thank you for using Dragonflye, and I will try to update soon.
Robert

**Comment by rpetit3** [comment]
This is fixed in v1.0.7 (https://github.com/rpetit3/dragonflye/releases/tag/v1.0.7)  `medaka` v1.5.0 changed how it reports the models. I've pinned the Bioconda recipe to always use >v1.5.0 of medaka.  The new version should be available from Bioconda soon.

Please feel free to reopen

**Comment by ArnieBerg** [comment]
Thankful for your quick action and looking forward to installing the update!
