### ISSUE TITLE
Outdated read length after trimming adapters

### ISSUE THREAD

**Issue by camilogarciabotero** [rpetit3/dragonflye#8]
Hi @rpetit3,

Thanks for working on `dragonflye` it is an awesome pipeline!
I found that there might be an outdated env variable that after trimming and quality filtering keeps sending the initial read length average.
 
https://github.com/rpetit3/dragonflye/blob/3757186157a8358db3032d2c1701cd2192697bbb/bin/dragonflye#L259

Cheers.

**Comment by rpetit3** [comment]
Nice catch! I think I've addressed this here: https://github.com/rpetit3/dragonflye/commit/5d9098368656919198915a570b6643443c5c0c2e

Going to play around with it a bit to see. 

Thanks for finding this!

**Comment by camilogarciabotero** [comment]
Hey!

Thank you for the quick response and potential solution!

**Comment by rpetit3** [comment]
Thanks again for catching this.

I've released v1.0.10 (https://github.com/rpetit3/dragonflye/releases/tag/v1.0.10) with a fix.
