### ISSUE TITLE
Expose nano-hq option

### ISSUE THREAD

**Issue by Mattstorey** [rpetit3/dragonflye#9]
Might be useful for data generated with the latest ONT chemistry (Q20+) and basecallers to have the `Flye --nano-hq` mode available. I found that this can't be added with the `--opts` flag as `--nano-raw` is hardcoded. Great tool!

**Comment by rpetit3** [comment]
Thank you for catching that. I'll go ahead and get this added

**Comment by rpetit3** [comment]
OK! I've released v1.0.12 (https://github.com/rpetit3/dragonflye/releases/tag/v1.0.12) which now includes `--nanohq` which switches Flay to `--nano-hq`

Thanks again for the feedback
